cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedListView.as_view(), name='breed_list'), 
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Add this for authentication
    path('autos/', include('autos.urls')),  # Add this for autos CRUD views
    path('cats/', include('cats.urls')),
]

cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

cats/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Cat, Breed
from django.urls import reverse_lazy

class CatList(LoginRequiredMixin, ListView):
    model = Cat
    template_name = 'cats/cat_list.html'

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ['nickname', 'weight', 'foods', 'breed']
    template_name = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ['nickname', 'weight', 'foods', 'breed']
    template_name = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    template_name = 'cats/cat_confirm_delete.html'
    success_url = reverse_lazy('cats:all')
    
class BreedListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'cats/breed_list.html' 
    success_url = reverse_lazy('cats:all') 

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = ['name']
    template_name = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:all')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = ['name']
    template_name = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:all')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    template_name = 'cats/breed_confirm_delete.html'
    success_url = reverse_lazy('cats:all')

cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Delete Breed</h1>

  <p>Are you sure you want to delete the breed: {{ breed.name }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <p>
        <a href="{% url 'cats:breed_delete' breed.id %}">Yes, delete.</a>
      </p>
      <p>
        <a href="{% url 'cats:all' %}">Cancel</a>
      </p>
  </form>
{% endblock %}

cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>{% if breed %}Update{% else %}Create{% endif %} Breed</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <p>
        <a href="{% url 'cats:all' %}">Cancel</a>
      </p>
  </form>
{% endblock %}

cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
          (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breeds in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
  <a href="{% url 'cats:all' %}">Back to cats</a>
{% endblock %}

cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Delete Cat</h1>

  <p>Are you sure you want to delete the cat: {{ cat.nickname }} ({{ cat.breed }})?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <p>
        <a href="{% url 'cats:cat_delete' cat.id %}">Yes, delete.</a>
      </p>
      <p>
        <a href="{% url 'cats:all' %}">Cancel</a>
      </p>
  </form>
{% endblock %}

cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>{% if cat %}Update{% else %}Create{% endif %} Cat</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <p>
        <a href="{% url 'cats:all' %}">Cancel</a>
      </p>
  </form>
{% endblock %}

cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cat List</h1>
  {% if cat_list %}
  <ul>
    {% for cat in cat_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:cat_create' %}">Add a cat</a></p>
  <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
  <p><a href="{% url 'cats:breed_list' %}">View breeds</a></p>
  <a href="{% url 'cats:all' %}">Back to cats</a>
{% endblock %}